#!/usr/bin/env bash

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

filepath=$1
server=$2
$user=$3
ssh_key=$4

scp -i "$ssh_key" -o StrictHostKeyChecking=no "$filepath" "$user@$server":~/
