#!/usr/bin/env bash
# Will Install nginx listening on port 80

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > sudo tee /var/www/html/index.html
sudo service nginx restart

