#!/usr/bin/env bash
# Will Configure a new Nginx server
# such that /redirect_me redirects to youtube

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo ufw enable
sudo ufw allow 'Nginx HTTP'

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart

