#!/usr/bin/env bash
# HTTP 404 Redirection handling

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'NGINX HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i '/server_name _;/a \
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        internal;\n\
    }' /etc/nginx/sites-available/default

    sudo service nginx start
