#!/usr/bin/env bash
# Create identical nginx config

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
