#!/usr/bin/env bash

sudo apt-get update -y
sudo apt-get upgrade -y

sudo apt-get -y install haproxy

# Configure haproxy
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 234523-web-01 34.207.83.75:80 check
    server 234523-web-02 18.204.5.248:80 check
"

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Enable on startup
sudo service haproxy start
