#!/usr/bin/env bash
# Configure NGINX to listen on port 80

NGINX_AVAILABLE="/etc/nginx/sites-available/default"
NGINX_ENABLED="/etc/nginx/sites-enabled/default"

# Start nginx
service nginx enable

# Remove the default Nginx configuration file if it exists
if [ -e "$NGINX_ENABLED" ]; then
    echo "Removing default Nginx configuration file"
    rm "$NGINX_ENABLED"
fi

# Create a symbolic link to enable the custom configuration
ln -s "$NGINX_AVAILABLE" "$NGINX_ENABLED"

# Restart Nginx to apply the changes
service nginx restart

