#!/usr/bin/env bash
# Configure NGINX to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx status > /dev/null 2>&1 || service nginx start
sudo service nginx restart
