#!/usr/bin/env bash
# Displays numbers from 1 to 100
# If the number is divisible by 3, it displays "Fizz"
# If the number is divisible by 5, it displays "Buzz"
# If the number is divisible by both 3 and 5, it displays "FizzBuzz"
for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
