#!/usr/bin/env bash
# Displays best school 10 times using an then on the 9th iteration, displays "Hi" instead of "Best School"

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi

	echo "Best School"
	(( i++))
done
