#!/usr/bin/env bash
# Displays best school 10 times using an
# then on the 3rd iteration, displays "bad luck"
# instead of "Best School"

i=1

while [ $i -lt 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
