#!/usr/bin/env bash

# Displays best school 10 times using an
#then on the 3rd iteration, displays "bad luck"
# instead of "Best School"

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
