#!/usr/bin/env bash
# Configures an ubuntu server


cp /etc/hosts ~/hosts.new
# Copies the configuration

echo "127.0.0.2	localhost" >> ~/hosts.new
# Then writes the localhost Ip to the new hosts file

echo "8.8.8.8	facebook.com" >> ~/hosts.new
# Repeats the same for facebook

cp -f ~/hosts.new /etc/hosts
# Finally copies the new configs
