#!/usr/bin/env bash
# Set Nginx user

sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

sed -i '/listen\s*80;/a \    listen 8080 default_server;' /etc/nginx/sites-available/default
sudo service nginx reload

