#!/usr/bin/env bash
# Change user to nginx
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod a+rw /etc/nginx/nginx.conf
pkill apache2 && sudo -u nginx service nginx start

